
services:
  ###########################################################################
  #                            TRAEFIK
  ###########################################################################
  traefik:
    image: "traefik"
    container_name: la-sup-traefik
    restart: always
    command:
      - "--accesslog=true"                
      - "--accesslog.filepath=/logs/access.log" 
      - "--accesslog.bufferingSize=100"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log:/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
      - ./config/.passwd:/etc/traefik/.passwd
    networks:
      - la-sup-network
    labels:
      - "traefik.docker.network=monitoring"

  ###########################################################################
  #                            LA-SUP-DASHBOARD
  ###########################################################################
  la-sup:
    build: ./la-sup-dashboard/
    container_name: la-sup-dashboard
    ports:
      - "127.0.0.1:1604:80"
    restart: unless-stopped
    networks:
      - la-sup-network
    labels:
      - traefik.enable=true

      # HTTP Router
      - traefik.http.routers.la-sup-http.rule=Host(`la-sup-dashboard.${DOMAIN_NAME}`)
      - traefik.http.routers.la-sup-http.entrypoints=web

      # HTTPS Router
      - traefik.http.routers.la-sup-https.rule=Host(`la-sup-dashboard.${DOMAIN_NAME}`)
      - traefik.http.routers.la-sup-https.entrypoints=websecure
      - traefik.http.routers.la-sup-https.tls.certresolver=mytlschallenge


  ###########################################################################
  #                            PROMETHEUS
  ###########################################################################
  prometheus:
    image: prom/prometheus
    container_name: la-sup-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - la-sup-network
    labels:
      - traefik.enable=true

      # HTTP Router
      - traefik.http.routers.prometheus-http.rule=Host(`la-sup-prometheus.${DOMAIN_NAME}`)
      - traefik.http.routers.prometheus-http.entrypoints=web

      # HTTPS Router
      - traefik.http.routers.prometheus-https.rule=Host(`la-sup-prometheus.${DOMAIN_NAME}`)
      - traefik.http.routers.prometheus-https.entrypoints=websecure
      - traefik.http.routers.prometheus-https.tls.certresolver=mytlschallenge

  ###########################################################################
  #                            GRAFANA
  ###########################################################################
  grafana:
    image: grafana/grafana
    container_name: la-sup-grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - la-sup-network
    labels:
      - traefik.enable=true

      # HTTP Router
      - traefik.http.routers.grafana-http.rule=Host(`la-sup-grafana.${DOMAIN_NAME}`)
      - traefik.http.routers.grafana-http.entrypoints=web

      # HTTPS Router
      - traefik.http.routers.grafana-https.rule=Host(`la-sup-grafana.${DOMAIN_NAME}`)
      - traefik.http.routers.grafana-https.entrypoints=websecure
      - traefik.http.routers.grafana-https.tls.certresolver=mytlschallenge

  ###########################################################################
  #                            LOKI
  ###########################################################################
  loki:
    image: grafana/loki
    container_name: la-sup-loki
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./config/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    networks:
      - la-sup-network
    labels:
      - traefik.enable=true

      # HTTP Router
      - traefik.http.routers.loki-http.rule=Host(`la-sup-loki.${DOMAIN_NAME}`)
      - traefik.http.routers.loki-http.entrypoints=web

      # HTTPS Router
      - traefik.http.routers.loki-https.rule=Host(`la-sup-loki.${DOMAIN_NAME}`)
      - traefik.http.routers.loki-https.entrypoints=websecure
      - traefik.http.routers.loki-https.tls.certresolver=mytlschallenge

  ###########################################################################
  #                            N8N
  ###########################################################################
  n8n:
    container_name: la-sup-n8n
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "127.0.0.1:5678:5678"
    networks:
      - la-sup-network
    labels:
      - traefik.enable=true

      # HTTP Router
      - traefik.http.routers.n8n-http.rule=Host(`la-sup-n8n.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n-http.entrypoints=web

      # HTTPS Router
      - traefik.http.routers.n8n-https.rule=Host(`la-sup-n8n.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n-https.entrypoints=websecure
      - traefik.http.routers.n8n-https.tls.certresolver=mytlschallenge

networks:
  la-sup-network:

volumes:
  loki_data:
  prometheus_data:
  grafana_data:
  traefik_data:
  n8n_data:
