server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: https://la-sup.com/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    file_sd_configs:
      - files:
          - /etc/promtail/system_logs.yaml
    relabel_configs:
      - source_labels: [__path__]
        regex: ".*/([^/]+)$"
        target_label: filename
    static_configs:
      - targets:
          - localhost
        labels:
          job: "system_logs"
          host: "<HOST_LABEL>"

  - job_name: security_logs
    file_sd_configs:
      - files:
          - /etc/promtail/security_logs.yaml
    relabel_configs:
      - source_labels: [__path__]
        regex: ".*/([^/]+)$"
        target_label: filename
    static_configs:
      - targets:
          - localhost
        labels:
          job: "security_logs"
          host: "<HOST_LABEL>"

  - job_name: docker_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - action: replace
        target_label: job
        replacement: integrations/docker
      - source_labels:
          - __meta_docker_container_id
        target_label: job
      - source_labels:
          - __meta_docker_container_name
        regex: '/(.*)'
        target_label: container
      - source_labels:
          - __meta_docker_container_log_stream
        target_label: stream
      - source_labels:
          - __meta_docker_container_label_service
        target_label: service
      - target_label: host
        replacement: "<HOST_LABEL>"
